language: node_js
node_js:
  - "4.1"
sudo: required
services:
  - docker
install:
  - make developer
  - npm install
  - make test
# Post to Slack
notifications:
  slack: jencateam:m1Z9iUkUDDtl77hoUlm4SQEb

