FROM node:5.4.0-slim
MAINTAINER connor@jenca.io
WORKDIR /app
COPY package.json /app/package.json
RUN npm install
# mount the code at runtime to /app/code
RUN mkdir -p /app/code
WORKDIR /app/code
ENTRYPOINT ["npm", "run"]
CMD ["build"]