FROM node:5.2.0-slim
MAINTAINER connor@jenca.io
WORKDIR /app
COPY package.json /app/package.json
RUN npm install
# mount the code (src) at runtime to /app/src
COPY ./src /app/src
COPY ./.babelrc /app/.babelrc
COPY ./webpack.config.js /app/webpack.config.js
ENTRYPOINT ["npm", "run"]
CMD ["build"]